INSERT INTO tennisdb.tournaments
(event_slug,event_id,title_text,date_text,full_text,overview_url,source_url,fetched_at,points,tour_type)
VALUES
(NULL,NULL,'UniCredit Iasi Open','13-JUL','UniCredit Iasi Open | Iasi - C','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'Athens Open','13-JUL','Athens Open | Athens - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'MSC Hamburg Ladies Open','20-JUL','MSC Hamburg Ladies Open | Hamburg - C','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'Livesport Prague Open 2026','20-JUL','Livesport Prague Open 2026 | Prague - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'Mubadala DC Open','27-JUL','Mubadala DC Open | Washington DC - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'The Memphis Classic','27-JUL','The Memphis Classic | Memphis - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'National Bank Open presented by Rogers','3-AUG','National Bank Open presented by Rogers | Toronto - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'1000','WTA'),
(NULL,NULL,'Cincinnati Open','10-AUG','Cincinnati Open | Cincinnati - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'1000','WTA'),
(NULL,NULL,'Abierto GNP Seguros','24-AUG','Abierto GNP Seguros | Monterrey - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'US Open','31-AUG','US Open | New York - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'2000','WTA'),
(NULL,NULL,'Guadalajara Open presented by Santander','14-SEP','Guadalajara Open presented by Santander | Guadalajara - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'SP Open','14-SEP','SP Open | São Paulo - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'Singapore Tennis Open','21-SEP','Singapore Tennis Open | Singapore - I H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'Korea Open','21-SEP','Korea Open | Seoul - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'China Open','28-SEP','China Open | Beijing - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'1000','WTA'),
(NULL,NULL,'Nordea Open','6-JUL','Nordea Open | Bastad, Sweden CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Grand Est Open 88','6-JUL','Grand Est Open 88 | Contrexeville, France CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Cerity Partners Hall of Fame Open for the Van Alen Cup Presented by the Margaret Fund','6-JUL','Cerity Partners Hall of Fame Open for the Van Alen Cup Presented by the Margaret Fund | Newport, Rhode Island, USA GRASS','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Enka Open','13-JUL','Enka Open | Istanbul, Turkey HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Generali Open Ladies Kitzbühel','13-JUL','Generali Open Ladies Kitzbühel | Kitzbuhel, Austria CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'ATV Bancomat Tennis Open','13-JUL','ATV Bancomat Tennis Open | Rome, Italy CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'37° Palermo Ladies Open','20-JUL','37° Palermo Ladies Open | Palermo, Italy CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'AXERIA Open 2026 powered by INTARO Sport','27-JUL','AXERIA Open 2026 powered by INTARO Sport | Targu Mures, Romania CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Odlum Brown VanOpen','27-JUL','Odlum Brown VanOpen | Vancouver, Canada HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Warsaw T-mobile Polish Open','3-AUG','Warsaw T-mobile Polish Open | Warsaw, Poland HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Ennoble Care Philly Open','24-AUG','Ennoble Care Philly Open | Philadelphia, Pennsylvania, USA HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'ATIK Antalya Open','7-SEP','ATIK Antalya Open | Antalya, Turkey CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Kia Open','7-SEP','Kia Open | Barranquilla, Colombia HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Montreux Nestlé Open','7-SEP','Montreux Nestlé Open | Montreux, Switzerland CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Caldas da Rainha Ladies Open','14-SEP','Caldas da Rainha Ladies Open | Caldas da Rainha, Portugal HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Zavarovalnica Triglav Ljubljana','14-SEP','Zavarovalnica Triglav Ljubljana | Ljubljana, Slovenia CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'BBVA Open Internacional de Valencia','14-SEP','BBVA Open Internacional de Valencia | Valencia, Spain CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Ankara Open','21-SEP','Ankara Open | Ankara, Turkey HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Eupago Porto Open','21-SEP','Eupago Porto Open | Porto, Portugal HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Delta Motors Tolentino Open','21-SEP','Delta Motors Tolentino Open | Tolentino, Italy CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Adana Open','28-SEP','Adana Open | Adana, Turkey HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Jingshan Tennis Open','28-SEP','Jingshan Tennis Open | Jingshan, China HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125');
