INSERT INTO tennisdb.tournaments
(event_slug,event_id,title_text,date_text,full_text,overview_url,source_url,fetched_at,points,tour_type)
VALUES
(NULL,NULL,'United Cup','5-JAN','United Cup | Perth, Sydney - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'ASB Classic','5-JAN','ASB Classic | Auckland - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'Brisbane International','5-JAN','Brisbane International | Brisbane - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'Adelaide International','12-JAN','Adelaide International | Adelaide - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'Hobart International','12-JAN','Hobart International | Hobart - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'Australian Open','19-JAN','Australian Open | Melbourne - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'2000','WTA'),
(NULL,NULL,'Mubadala Abu Dhabi Open','2-FEB','Mubadala Abu Dhabi Open presented by Abu Dhabi Sports Council | Abu Dhabi - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'Transylvania Open','2-FEB','Transylvania Open powered by Kaufland | Cluj-Napoca - IH','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'Ostrava','2-FEB','Ostrava | Ostrava - IH','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'Qatar TotalEnergies Open 2026','9-FEB','Qatar TotalEnergies Open 2026 | Doha - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'1000','WTA'),
(NULL,NULL,'Dubai Duty Free Tennis Championships','16-FEB','Dubai Duty Free Tennis Championships | Dubai - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'1000','WTA'),
(NULL,NULL,'Merida Open AKRON','23-FEB','Merida Open AKRON | Merida - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'ATX Open','23-FEB','ATX Open | Austin - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'BNP Paribas Open','2-MAR','BNP Paribas Open | Indian Wells - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'1000','WTA'),
(NULL,NULL,'Miami Open presented by Itaú','16-MAR','Miami Open presented by Itaú | Miami - H','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'1000','WTA'),
(NULL,NULL,'Credit One Charleston Open','30-MAR','Credit One Charleston Open | Charleston - C','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'2026 Colsanitas Cup','30-MAR','2026 Colsanitas Cup | Bogota - C','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'Workday Canberra Open','5-JAN','Workday Canberra Open | Canberra, Australia HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Philippine Women''s Open','26-JAN','Philippine Women''s Open | Manila, Philippines HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'L&T Mumbai Open','2-FEB','L&T Mumbai Open | Mumbai, India HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Oeiras 1 - Jamor Indoor','9-FEB','Oeiras 1 - Jamor Indoor | Oeiras, Portugal I HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Open Arena Les Sables d''Olonne','16-FEB','Open Arena Les Sables d''Olonne | Les Sables d''Olonne, France I HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Dow Tennis Classic','16-FEB','Dow Tennis Classic | Midland, Michigan, USA I HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Oeiras 2 - Jamor Indoor','16-FEB','Oeiras 2 - Jamor Indoor | Oeiras, Portugal I HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Megasaray Hotels Open','23-FEB','Megasaray Hotels Open | Antalya, Turkey CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Megasaray Hotels Open','2-MAR','Megasaray Hotels Open | Antalya, Turkey CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Megasaray Hotels Open','9-MAR','Megasaray Hotels Open | Antalya, Turkey CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Austin 125','9-MAR','Austin 125 | Austin, Texas, USA HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Dubrovnik Open','23-MAR','Dubrovnik Open | Dubrovnik, Croatia CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125');
