INSERT INTO tennisdb.tournaments
(event_slug,event_id,title_text,date_text,full_text,overview_url,source_url,fetched_at,points,tour_type)
VALUES
(NULL,NULL,'Upper Austria Ladies Linz','6-APR','Upper Austria Ladies Linz | Linz - I C','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'Porsche Tennis Grand Prix','13-APR','Porsche Tennis Grand Prix | Stuttgart - I C','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'Open Capfinances Rouen Métropole','13-APR','Open Capfinances Rouen Métropole | Rouen - I C','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'Mutua Madrid Open','20-APR','Mutua Madrid Open | Madrid - C','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'1000','WTA'),
(NULL,NULL,'Internazionali BNL d’Italia','4-MAY','Internazionali BNL d’Italia | Rome - C','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'1000','WTA'),
(NULL,NULL,'Internationaux de Strasbourg','18-MAY','Internationaux de Strasbourg | Strasbourg - C','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'Grand Prix Son Altesse Royale La Princesse Lalla Meryem','18-MAY','Grand Prix Son Altesse Royale La Princesse Lalla Meryem | Rabat - C','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'Roland-Garros','25-MAY','Roland-Garros | Paris - C','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'2000','WTA'),
(NULL,NULL,'The HSBC Championships','8-JUN','The HSBC Championships | London - G','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'Libéma Open','8-JUN','Libéma Open | s''Hertogenbosch - G','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'Berlin Tennis Open','15-JUN','Berlin Tennis Open | Berlin - G','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'Lexus Nottingham Open','15-JUN','Lexus Nottingham Open | Nottingham - G','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'Bad Homburg Open powered by Solarwatt','22-JUN','Bad Homburg Open powered by Solarwatt | Bad Homburg - G','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'500','WTA'),
(NULL,NULL,'Lexus Eastbourne Open','22-JUN','Lexus Eastbourne Open | Eastbourne - G','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'250','WTA'),
(NULL,NULL,'The Championships','29-JUN','The Championships | Wimbledon - G','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'2000','WTA'),
(NULL,NULL,'Open Villa de Madrid by Silverway Asset Management','6-APR','Open Villa de Madrid by Silverway Asset Management | Madrid, Spain CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Oeiras Ladies Open','13-APR','Oeiras Ladies Open | Oeiras, Portugal CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Oeiras Open CETO','20-APR','Oeiras Open CETO | Oeiras, Portugal CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'L''Open 35 de Saint-Malo','27-APR','L''Open 35 de Saint-Malo | Saint Malo, France CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Catalonia Open Solgironès','27-APR','Catalonia Open Solgironès | La Bisbal d''Emporda, Spain CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Huzhou Open','27-APR','Huzhou Open | Huzhou, China CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Istanbul Open','4-MAY','Istanbul Open | Istanbul, Turkey CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Jiangxi Open','4-MAY','Jiangxi Open | Jiujiang, China HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Parma Ladies Open presented by IREN','11-MAY','Parma Ladies Open presented by IREN | Parma, Italy CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Trophèe Clarins','11-MAY','Trophèe Clarins | Paris, France CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Makarska Open','1-JUN','Makarska Open | Makarska, Croatia CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Open delle Puglie Trofeo','1-JUN','Open delle Puglie Trofeo | Foggia, Italy CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Lexus Birmingham Open','1-JUN','Lexus Birmingham Open | Birmingham, Great Britain GRASS','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Lexus Ilkley Open','8-JUN','Lexus Ilkley Open | Ilkley, Great Britain GRASS','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Memorial Eugenio Fontana','8-JUN','Memorial Eugenio Fontana | Modena, Italy CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Internazionali Femminili Di Brescia','15-JUN','Internazionali Femminili Di Brescia | Brescia, Italy CLAY','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125'),
(NULL,NULL,'Figueira da Foz Ladies Open','15-JUN','Figueira da Foz Ladies Open | Figueira da Foz, Portugal HARD','https://www.wtatennis.com/tournaments','https://www.wtatennis.com/tournaments',NOW(),'125','WTA125');
