CREATE TABLE IF NOT EXISTS tennisdb.official_rankings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_slug TEXT NOT NULL,
    tour TEXT NOT NULL,
    category TEXT NOT NULL,
    rank_text TEXT,
    rank_value INTEGER,
    player TEXT NOT NULL,
    age INTEGER,
    country TEXT,
    points_text TEXT,
    points_value INTEGER,
    career_high TEXT,
    change_text TEXT,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_official_rankings_source ON tennisdb.official_rankings USING btree (source_slug);
CREATE INDEX IF NOT EXISTS idx_official_rankings_player ON tennisdb.official_rankings USING btree (player);
